orbs:
  slack: circleci/slack@4.2.0

version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo Hello!
      #- run: echo ${FIVEHUNDRED}


workflows:
  build:
    jobs:
    - build:
        context: Demos-context

