version: 2.1
orbs:
  hello-world: sample-orbs/hello-world@0.0.10
  windows: circleci/windows@2.4.0

jobs:
  echo-win-version:
    executor: windows/default
    steps:
      - run: echo [System.Environment]::OSVersion.Version

workflows:
  main:
    jobs:
      - echo-win-version