orbs:
  slack: circleci/slack@4.2.0

version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo Hello!
      - run: |
          echo "export __SLACK_CHANNEL=\"jennings\"" | tee -a $BASH_ENV
      - run: |
          echo $__SLACK_CHANNEL
      - slack/notify:
            channel: $__SLACK_CHANNEL
            ignore_errors: false
            custom: |
              {
                  "blocks": [
                      {
                          "type": "section",
                          "text": {
                              "type": "mrkdwn",
                              "text": "$CIRCLE_USERNAME's build of \n<$CIRCLE_BUILD_URL|$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME>\n(<https://app.circleci.com/pipelines/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?branch=$CIRCLE_BRANCH|$CIRCLE_BRANCH>) \n- <$CIRCLE_BUILD_URL|$CIRCLE_JOB> finished"
                          }
                      }
                  ]
              }


workflows:
  build:
    jobs:
    - build:
        context: Demos-context

