version: 2.1
orbs:
  hello-world: sample-orbs/hello-world@0.0.10

jobs:
  echo:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: "Monitor CPU and memory usage"
          background: true
          command: |
            sleep 3
            echo "Time \| CPU \| Mem | tee /tmp/cpu_mem_util.log
            while true; do
              echo $(date +"%D %T %Z") \| $(top -bn1 | sed -n '/Cpu/p' | awk '{print $2 + $4}')%  \| $(free | grep Mem | awk '{printf "%.2f\n", $3/$2 * 100.0}')% | tee /tmp/cpu_mem_util.log
              sleep 1
            done
      - hello-world/echo-command
      - run: |
          dd if=/dev/random iflag=fullblock of=./randomFile1 bs=5M count=1
          sleep 5
          dd if=/dev/random iflag=fullblock of=./randomFile2 bs=10M count=1
          sleep 5
          dd if=/dev/random iflag=fullblock of=./randomFile3 bs=15M count=1
      - store_artifacts:
          path: /tmp/cpu_mem_util.log


workflows:
  main:
    jobs:
      - echo